/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Alert: typeof import('./src/components/Alert.vue')['default']
    Badge: typeof import('./src/components/Badge.vue')['default']
    Button: typeof import('./src/components/Button.vue')['default']
    CacheFileSettings: typeof import('./src/components/CacheFileSettings.vue')['default']
    Card: typeof import('./src/components/Card.vue')['default']
    ClashAPISettings: typeof import('./src/components/ClashAPISettings.vue')['default']
    DialerOptions: typeof import('./src/components/DialerOptions.vue')['default']
    DNSRules: typeof import('./src/components/DNSRules.vue')['default']
    DNSServers: typeof import('./src/components/DNSServers.vue')['default']
    DNSSettings: typeof import('./src/components/DNSSettings.vue')['default']
    FinalPolicy: typeof import('./src/components/FinalPolicy.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Input: typeof import('./src/components/Input.vue')['default']
    Loading: typeof import('./src/components/Loading.vue')['default']
    Modal: typeof import('./src/components/Modal.vue')['default']
    MonacoEditor: typeof import('./src/components/MonacoEditor.vue')['default']
    NodeList: typeof import('./src/components/NodeList.vue')['default']
    Notification: typeof import('./src/components/Notification.vue')['default']
    NotificationContainer: typeof import('./src/components/NotificationContainer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RoutingRuleItem: typeof import('./src/components/RoutingRuleItem.vue')['default']
    RoutingRules: typeof import('./src/components/RoutingRules.vue')['default']
    RuleSets: typeof import('./src/components/RuleSets.vue')['default']
    Select: typeof import('./src/components/Select.vue')['default']
    SelectExample: typeof import('./src/components/SelectExample.vue')['default']
    Sidebar: typeof import('./src/components/Sidebar.vue')['default']
    TabNav: typeof import('./src/components/TabNav.vue')['default']
    Textarea: typeof import('./src/components/Textarea.vue')['default']
    V2RayAPISettings: typeof import('./src/components/V2RayAPISettings.vue')['default']
  }
}
