/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutCard: typeof import('./src/components/AboutCard.vue')['default']
    Alert: typeof import('./src/components/Alert.vue')['default']
    AppUpdateCard: typeof import('./src/components/AppUpdateCard.vue')['default']
    Badge: typeof import('./src/components/Badge.vue')['default']
    Button: typeof import('./src/components/Button.vue')['default']
    CacheFileSettings: typeof import('./src/components/CacheFileSettings.vue')['default']
    Card: typeof import('./src/components/Card.vue')['default']
    ChipsField: typeof import('./src/components/ChipsField.vue')['default']
    ClashAPISettings: typeof import('./src/components/ClashAPISettings.vue')['default']
    ConfirmDialog: typeof import('./src/components/ConfirmDialog.vue')['default']
    DashboardDownloader: typeof import('./src/components/DashboardDownloader.vue')['default']
    DashboardUrlSelect: typeof import('./src/components/DashboardUrlSelect.vue')['default']
    DialerOptions: typeof import('./src/components/DialerOptions.vue')['default']
    DnsProbeCard: typeof import('./src/components/DnsProbeCard.vue')['default']
    DnsProbePanel: typeof import('./src/components/DnsProbePanel.vue')['default']
    DnsProbeTimeline: typeof import('./src/components/DnsProbeTimeline.vue')['default']
    DNSRuleConditions: typeof import('./src/components/DNSRuleConditions.vue')['default']
    DnsRuleFlow: typeof import('./src/components/DnsRuleFlow.vue')['default']
    DNSRules: typeof import('./src/components/DNSRules.vue')['default']
    DNSServers: typeof import('./src/components/DNSServers.vue')['default']
    DNSSettings: typeof import('./src/components/DNSSettings.vue')['default']
    FinalPolicy: typeof import('./src/components/FinalPolicy.vue')['default']
    GitHubAuthCard: typeof import('./src/components/GitHubAuthCard.vue')['default']
    HostsEditor: typeof import('./src/components/HostsEditor.vue')['default']
    Input: typeof import('./src/components/Input.vue')['default']
    JsonField: typeof import('./src/components/JsonField.vue')['default']
    LabeledField: typeof import('./src/components/LabeledField.vue')['default']
    LanguageSwitcher: typeof import('./src/components/LanguageSwitcher.vue')['default']
    List: typeof import('./src/components/List.vue')['default']
    ListField: typeof import('./src/components/ListField.vue')['default']
    ListRow: typeof import('./src/components/ListRow.vue')['default']
    Loading: typeof import('./src/components/Loading.vue')['default']
    Modal: typeof import('./src/components/Modal.vue')['default']
    MonacoDiffEditor: typeof import('./src/components/MonacoDiffEditor.vue')['default']
    MonacoEditor: typeof import('./src/components/MonacoEditor.vue')['default']
    NodeList: typeof import('./src/components/NodeList.vue')['default']
    OutboundsList: typeof import('./src/components/OutboundsList.vue')['default']
    PopConfirm: typeof import('./src/components/PopConfirm.vue')['default']
    RouteProbePanel: typeof import('./src/components/RouteProbePanel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouteRuleMatchers: typeof import('./src/components/RouteRuleMatchers.vue')['default']
    RouterView: typeof import('vue-router')['RouterView']
    RoutingRuleItem: typeof import('./src/components/RoutingRuleItem.vue')['default']
    RoutingRules: typeof import('./src/components/RoutingRules.vue')['default']
    RuleFlowPreview: typeof import('./src/components/RuleFlowPreview.vue')['default']
    RuleSets: typeof import('./src/components/RuleSets.vue')['default']
    SchemaFieldControl: typeof import('./src/components/SchemaFieldControl.vue')['default']
    SchemaFieldsEditor: typeof import('./src/components/SchemaFieldsEditor.vue')['default']
    Sidebar: typeof import('./src/components/Sidebar.vue')['default']
    SmartRoutingRuleWizard: typeof import('./src/components/SmartRoutingRuleWizard.vue')['default']
    StorageUsage: typeof import('./src/components/StorageUsage.vue')['default']
    SubscriptionInfoKeywords: typeof import('./src/components/SubscriptionInfoKeywords.vue')['default']
    SubscriptionsOverviewCard: typeof import('./src/components/SubscriptionsOverviewCard.vue')['default']
    Table: typeof import('./src/components/Table.vue')['default']
    TabNav: typeof import('./src/components/TabNav.vue')['default']
    Textarea: typeof import('./src/components/Textarea.vue')['default']
    Topbar: typeof import('./src/components/Topbar.vue')['default']
    UsersEditor: typeof import('./src/components/UsersEditor.vue')['default']
    V2RayAPISettings: typeof import('./src/components/V2RayAPISettings.vue')['default']
  }
}
