// Code generated by cmd/gen-option-schema. DO NOT EDIT.
//
// DNS rule action options, keyed by the `action` field of an entry in `dns.rules`.
//
// THE KEY IS `action`, NOT `type`. A DNS rule carries both: `type` selects the
// MATCHER shape ("default" or "logical") and `action` selects what happens once
// the rule matches. They vary independently, and an omitted `action` means
// "route".
//
// These fields share one flat JSON object with the rule's match conditions
// (`domain`, `rule_set`, `ip_cidr`, ...), which belong to no action and appear in
// no entry below. Pruning on action change must therefore remove only keys owned
// by another action — see pruneForeignFields in optionSchema.ts.
//
// Reflected from github.com/sagernet/sing-box v1.12.12 — the same option structs
// app/pkg/config/registry.go feeds to sing-box's own config parser, so this is
// what the running binary actually accepts.
//
// Regenerate with:  go generate ./app/pkg/config/
//
// This file says which fields EXIST and what shape they are. It deliberately
// says nothing about which ones matter, what they are called in the UI, or what
// order to show them in — that is editorial and lives in the matching curation
// file, which is type-checked against the keys below.

import type { OptionFieldInfo, OptionVersionNote } from './optionSchema'

export const DNS_RULE_ACTION_INVENTORY = {
  route: {
    client_subnet: { kind: 'cidr' },
    disable_cache: { kind: 'boolean' },
    rewrite_ttl: { kind: 'number' },
    server: { kind: 'string' },
    strategy: { kind: 'string' },
  },
  'route-options': {
    client_subnet: { kind: 'cidr' },
    disable_cache: { kind: 'boolean' },
    rewrite_ttl: { kind: 'number' },
    strategy: { kind: 'string' },
  },
  reject: {
    method: { kind: 'string' },
    no_drop: { kind: 'boolean' },
  },
  predefined: {
    answer: { kind: 'list', item: 'string' },
    extra: { kind: 'list', item: 'string' },
    ns: { kind: 'list', item: 'string' },
    rcode: { kind: 'string' },
  },
} as const satisfies Record<string, Record<string, OptionFieldInfo>>

/** Every DNSRuleAction type the backend registry can construct. */
export type DNSRuleActionTypeName = keyof typeof DNS_RULE_ACTION_INVENTORY

/**
 * The field keys valid for one DNSRuleAction type. Curation is keyed by this, so naming
 * a field sing-box does not have — or one it dropped in an upgrade — is a
 * compile error rather than an input that never binds.
 */
export type DNSRuleActionFieldKey<T extends DNSRuleActionTypeName> = Extract<
  keyof (typeof DNS_RULE_ACTION_INVENTORY)[T],
  string
>

export const DNS_RULE_ACTION_TYPE_NAMES = Object.keys(DNS_RULE_ACTION_INVENTORY) as DNSRuleActionTypeName[]

/**
 * Types sing-box has retired, with the versions from its own deprecation
 * table. `removed` is the one that bites: a type whose removed version is at
 * or below the INSTALLED binary is rejected, not merely discouraged.
 */
export const DNS_RULE_ACTION_TYPE_NOTES: Partial<Record<DNSRuleActionTypeName, OptionVersionNote>> = {
}
