// Code generated by cmd/gen-option-schema. DO NOT EDIT.
//
// DNS transport options, keyed by the `type` field of an entry in `dns.servers`.
// The legacy (untyped, `address`-based) shape is absent on purpose: sing-box
// upgrades it to a typed server while parsing, so it never reaches the UI.
//
// Reflected from github.com/sagernet/sing-box v1.12.12 — the same option structs
// app/pkg/config/registry.go feeds to sing-box's own config parser, so this is
// what the running binary actually accepts.
//
// Regenerate with:  go generate ./app/pkg/config/
//
// This file says which fields EXIST and what shape they are. It deliberately
// says nothing about which ones matter, what they are called in the UI, or what
// order to show them in — that is editorial and lives in the matching curation
// file, which is type-checked against the keys below.

import type { OptionFieldInfo, OptionVersionNote } from './optionSchema'

export const DNS_SERVER_INVENTORY = {
  udp: {
    bind_interface: { kind: 'string' },
    connect_timeout: { kind: 'duration' },
    detour: { kind: 'string' },
    domain_resolver: { kind: 'object' },
    domain_strategy: { kind: 'string', deprecated: true, since: '1.12.0', removed: '1.14.0' },
    fallback_delay: { kind: 'duration' },
    fallback_network_type: { kind: 'list', item: 'number' },
    inet4_bind_address: { kind: 'address' },
    inet6_bind_address: { kind: 'address' },
    netns: { kind: 'string' },
    network_strategy: { kind: 'number' },
    network_type: { kind: 'list', item: 'number' },
    protect_path: { kind: 'string' },
    reuse_addr: { kind: 'boolean' },
    routing_mark: { kind: 'number' },
    server: { kind: 'string' },
    server_port: { kind: 'number' },
    tcp_fast_open: { kind: 'boolean' },
    tcp_multi_path: { kind: 'boolean' },
    udp_fragment: { kind: 'boolean' },
  },
  tcp: {
    bind_interface: { kind: 'string' },
    connect_timeout: { kind: 'duration' },
    detour: { kind: 'string' },
    domain_resolver: { kind: 'object' },
    domain_strategy: { kind: 'string', deprecated: true, since: '1.12.0', removed: '1.14.0' },
    fallback_delay: { kind: 'duration' },
    fallback_network_type: { kind: 'list', item: 'number' },
    inet4_bind_address: { kind: 'address' },
    inet6_bind_address: { kind: 'address' },
    netns: { kind: 'string' },
    network_strategy: { kind: 'number' },
    network_type: { kind: 'list', item: 'number' },
    protect_path: { kind: 'string' },
    reuse_addr: { kind: 'boolean' },
    routing_mark: { kind: 'number' },
    server: { kind: 'string' },
    server_port: { kind: 'number' },
    tcp_fast_open: { kind: 'boolean' },
    tcp_multi_path: { kind: 'boolean' },
    udp_fragment: { kind: 'boolean' },
  },
  tls: {
    bind_interface: { kind: 'string' },
    connect_timeout: { kind: 'duration' },
    detour: { kind: 'string' },
    domain_resolver: { kind: 'object' },
    domain_strategy: { kind: 'string', deprecated: true, since: '1.12.0', removed: '1.14.0' },
    fallback_delay: { kind: 'duration' },
    fallback_network_type: { kind: 'list', item: 'number' },
    inet4_bind_address: { kind: 'address' },
    inet6_bind_address: { kind: 'address' },
    netns: { kind: 'string' },
    network_strategy: { kind: 'number' },
    network_type: { kind: 'list', item: 'number' },
    protect_path: { kind: 'string' },
    reuse_addr: { kind: 'boolean' },
    routing_mark: { kind: 'number' },
    server: { kind: 'string' },
    server_port: { kind: 'number' },
    tcp_fast_open: { kind: 'boolean' },
    tcp_multi_path: { kind: 'boolean' },
    tls: { kind: 'object' },
    udp_fragment: { kind: 'boolean' },
  },
  quic: {
    bind_interface: { kind: 'string' },
    connect_timeout: { kind: 'duration' },
    detour: { kind: 'string' },
    domain_resolver: { kind: 'object' },
    domain_strategy: { kind: 'string', deprecated: true, since: '1.12.0', removed: '1.14.0' },
    fallback_delay: { kind: 'duration' },
    fallback_network_type: { kind: 'list', item: 'number' },
    inet4_bind_address: { kind: 'address' },
    inet6_bind_address: { kind: 'address' },
    netns: { kind: 'string' },
    network_strategy: { kind: 'number' },
    network_type: { kind: 'list', item: 'number' },
    protect_path: { kind: 'string' },
    reuse_addr: { kind: 'boolean' },
    routing_mark: { kind: 'number' },
    server: { kind: 'string' },
    server_port: { kind: 'number' },
    tcp_fast_open: { kind: 'boolean' },
    tcp_multi_path: { kind: 'boolean' },
    udp_fragment: { kind: 'boolean' },
  },
  https: {
    bind_interface: { kind: 'string' },
    connect_timeout: { kind: 'duration' },
    detour: { kind: 'string' },
    domain_resolver: { kind: 'object' },
    domain_strategy: { kind: 'string', deprecated: true, since: '1.12.0', removed: '1.14.0' },
    fallback_delay: { kind: 'duration' },
    fallback_network_type: { kind: 'list', item: 'number' },
    headers: { kind: 'object' },
    inet4_bind_address: { kind: 'address' },
    inet6_bind_address: { kind: 'address' },
    method: { kind: 'string' },
    netns: { kind: 'string' },
    network_strategy: { kind: 'number' },
    network_type: { kind: 'list', item: 'number' },
    path: { kind: 'string' },
    protect_path: { kind: 'string' },
    reuse_addr: { kind: 'boolean' },
    routing_mark: { kind: 'number' },
    server: { kind: 'string' },
    server_port: { kind: 'number' },
    tcp_fast_open: { kind: 'boolean' },
    tcp_multi_path: { kind: 'boolean' },
    tls: { kind: 'object' },
    udp_fragment: { kind: 'boolean' },
  },
  h3: {
    bind_interface: { kind: 'string' },
    connect_timeout: { kind: 'duration' },
    detour: { kind: 'string' },
    domain_resolver: { kind: 'object' },
    domain_strategy: { kind: 'string', deprecated: true, since: '1.12.0', removed: '1.14.0' },
    fallback_delay: { kind: 'duration' },
    fallback_network_type: { kind: 'list', item: 'number' },
    headers: { kind: 'object' },
    inet4_bind_address: { kind: 'address' },
    inet6_bind_address: { kind: 'address' },
    method: { kind: 'string' },
    netns: { kind: 'string' },
    network_strategy: { kind: 'number' },
    network_type: { kind: 'list', item: 'number' },
    path: { kind: 'string' },
    protect_path: { kind: 'string' },
    reuse_addr: { kind: 'boolean' },
    routing_mark: { kind: 'number' },
    server: { kind: 'string' },
    server_port: { kind: 'number' },
    tcp_fast_open: { kind: 'boolean' },
    tcp_multi_path: { kind: 'boolean' },
    tls: { kind: 'object' },
    udp_fragment: { kind: 'boolean' },
  },
  local: {
    bind_interface: { kind: 'string' },
    connect_timeout: { kind: 'duration' },
    detour: { kind: 'string' },
    domain_resolver: { kind: 'object' },
    domain_strategy: { kind: 'string', deprecated: true, since: '1.12.0', removed: '1.14.0' },
    fallback_delay: { kind: 'duration' },
    fallback_network_type: { kind: 'list', item: 'number' },
    inet4_bind_address: { kind: 'address' },
    inet6_bind_address: { kind: 'address' },
    netns: { kind: 'string' },
    network_strategy: { kind: 'number' },
    network_type: { kind: 'list', item: 'number' },
    protect_path: { kind: 'string' },
    reuse_addr: { kind: 'boolean' },
    routing_mark: { kind: 'number' },
    tcp_fast_open: { kind: 'boolean' },
    tcp_multi_path: { kind: 'boolean' },
    udp_fragment: { kind: 'boolean' },
  },
  hosts: {
    path: { kind: 'list', item: 'string' },
    predefined: { kind: 'object' },
  },
  fakeip: {
    inet4_range: { kind: 'cidr' },
    inet6_range: { kind: 'cidr' },
  },
  dhcp: {
    bind_interface: { kind: 'string' },
    connect_timeout: { kind: 'duration' },
    detour: { kind: 'string' },
    domain_resolver: { kind: 'object' },
    domain_strategy: { kind: 'string', deprecated: true, since: '1.12.0', removed: '1.14.0' },
    fallback_delay: { kind: 'duration' },
    fallback_network_type: { kind: 'list', item: 'number' },
    inet4_bind_address: { kind: 'address' },
    inet6_bind_address: { kind: 'address' },
    interface: { kind: 'string' },
    netns: { kind: 'string' },
    network_strategy: { kind: 'number' },
    network_type: { kind: 'list', item: 'number' },
    protect_path: { kind: 'string' },
    reuse_addr: { kind: 'boolean' },
    routing_mark: { kind: 'number' },
    tcp_fast_open: { kind: 'boolean' },
    tcp_multi_path: { kind: 'boolean' },
    udp_fragment: { kind: 'boolean' },
  },
  tailscale: {
    accept_default_resolvers: { kind: 'boolean' },
    endpoint: { kind: 'string' },
  },
} as const satisfies Record<string, Record<string, OptionFieldInfo>>

/** Every DNSServer type the backend registry can construct. */
export type DNSServerTypeName = keyof typeof DNS_SERVER_INVENTORY

/**
 * The field keys valid for one DNSServer type. Curation is keyed by this, so naming
 * a field sing-box does not have — or one it dropped in an upgrade — is a
 * compile error rather than an input that never binds.
 */
export type DNSServerFieldKey<T extends DNSServerTypeName> = Extract<
  keyof (typeof DNS_SERVER_INVENTORY)[T],
  string
>

export const DNS_SERVER_TYPE_NAMES = Object.keys(DNS_SERVER_INVENTORY) as DNSServerTypeName[]

/**
 * Types sing-box has retired, with the versions from its own deprecation
 * table. `removed` is the one that bites: a type whose removed version is at
 * or below the INSTALLED binary is rejected, not merely discouraged.
 */
export const DNS_SERVER_TYPE_NOTES: Partial<Record<DNSServerTypeName, OptionVersionNote>> = {
}
