// Code generated by cmd/gen-option-schema. DO NOT EDIT.
//
// Route rule matching conditions — the `option.RawDefaultRule` half of an entry
// in `route.rules`.
//
// UNLIKE EVERY OTHER DOMAIN HERE, THIS ONE IS NOT POLYMORPHIC. There is exactly
// one entry, "default", because the matchers are a single flat struct with no
// discriminator. The generator's shape is reused only to avoid a second code
// path; "logical" is absent because a logical rule has no matchers of its own.
//
// Grouping (rule set / content / context) is editorial and lives in the curation
// file — see routeRuleMatcherFields.ts for why content and context differ.
//
// Reflected from github.com/sagernet/sing-box v1.12.12 — the same option structs
// app/pkg/config/registry.go feeds to sing-box's own config parser, so this is
// what the running binary actually accepts.
//
// Regenerate with:  go generate ./app/pkg/config/
//
// This file says which fields EXIST and what shape they are. It deliberately
// says nothing about which ones matter, what they are called in the UI, or what
// order to show them in — that is editorial and lives in the matching curation
// file, which is type-checked against the keys below.

import type { OptionFieldInfo, OptionVersionNote } from './optionSchema'

export const ROUTE_RULE_MATCHER_INVENTORY = {
  default: {
    auth_user: { kind: 'list', item: 'string' },
    clash_mode: { kind: 'string' },
    client: { kind: 'list', item: 'string' },
    domain: { kind: 'list', item: 'string' },
    domain_keyword: { kind: 'list', item: 'string' },
    domain_regex: { kind: 'list', item: 'string' },
    domain_suffix: { kind: 'list', item: 'string' },
    geoip: { kind: 'list', item: 'string', deprecated: true, since: '1.8.0', removed: '1.12.0' },
    geosite: { kind: 'list', item: 'string', deprecated: true, since: '1.8.0', removed: '1.12.0' },
    inbound: { kind: 'list', item: 'string' },
    invert: { kind: 'boolean' },
    ip_cidr: { kind: 'list', item: 'string' },
    ip_is_private: { kind: 'boolean' },
    ip_version: { kind: 'number' },
    network: { kind: 'list', item: 'string' },
    network_is_constrained: { kind: 'boolean' },
    network_is_expensive: { kind: 'boolean' },
    network_type: { kind: 'list', item: 'string' },
    package_name: { kind: 'list', item: 'string' },
    port: { kind: 'list', item: 'number' },
    port_range: { kind: 'list', item: 'string' },
    process_name: { kind: 'list', item: 'string' },
    process_path: { kind: 'list', item: 'string' },
    process_path_regex: { kind: 'list', item: 'string' },
    protocol: { kind: 'list', item: 'string' },
    rule_set: { kind: 'list', item: 'string' },
    rule_set_ip_cidr_match_source: { kind: 'boolean' },
    rule_set_ipcidr_match_source: { kind: 'boolean', deprecated: true, since: '1.10.0', removed: '1.11.0' },
    source_geoip: { kind: 'list', item: 'string', deprecated: true, since: '1.8.0', removed: '1.12.0' },
    source_ip_cidr: { kind: 'list', item: 'string' },
    source_ip_is_private: { kind: 'boolean' },
    source_port: { kind: 'list', item: 'number' },
    source_port_range: { kind: 'list', item: 'string' },
    user: { kind: 'list', item: 'string' },
    user_id: { kind: 'list', item: 'number' },
    wifi_bssid: { kind: 'list', item: 'string' },
    wifi_ssid: { kind: 'list', item: 'string' },
  },
} as const satisfies Record<string, Record<string, OptionFieldInfo>>

/** Every RouteRuleMatcher type the backend registry can construct. */
export type RouteRuleMatcherTypeName = keyof typeof ROUTE_RULE_MATCHER_INVENTORY

/**
 * The field keys valid for one RouteRuleMatcher type. Curation is keyed by this, so naming
 * a field sing-box does not have — or one it dropped in an upgrade — is a
 * compile error rather than an input that never binds.
 */
export type RouteRuleMatcherFieldKey<T extends RouteRuleMatcherTypeName> = Extract<
  keyof (typeof ROUTE_RULE_MATCHER_INVENTORY)[T],
  string
>

export const ROUTE_RULE_MATCHER_TYPE_NAMES = Object.keys(ROUTE_RULE_MATCHER_INVENTORY) as RouteRuleMatcherTypeName[]

/**
 * Types sing-box has retired, with the versions from its own deprecation
 * table. `removed` is the one that bites: a type whose removed version is at
 * or below the INSTALLED binary is rejected, not merely discouraged.
 */
export const ROUTE_RULE_MATCHER_TYPE_NOTES: Partial<Record<RouteRuleMatcherTypeName, OptionVersionNote>> = {
}
