// Code generated by cmd/gen-option-schema. DO NOT EDIT.
//
// Route rule action options, keyed by the `action` field of an entry in `route.rules`.
//
// THE KEY IS `action`, NOT `type` — a route rule uses `type` for the matcher
// shape ("default"/"logical"). An omitted `action` means "route".
//
// This is NOT the same set as DNS rule actions. `direct`, `hijack-dns`, `sniff`
// and `resolve` are route-only; `predefined` is DNS-only; the rest are shared.
//
// These fields share one flat JSON object with the rule's matchers, which belong
// to no action — prune with pruneForeignFields, never pruneForType.
//
// Reflected from github.com/sagernet/sing-box v1.12.12 — the same option structs
// app/pkg/config/registry.go feeds to sing-box's own config parser, so this is
// what the running binary actually accepts.
//
// Regenerate with:  go generate ./app/pkg/config/
//
// This file says which fields EXIST and what shape they are. It deliberately
// says nothing about which ones matter, what they are called in the UI, or what
// order to show them in — that is editorial and lives in the matching curation
// file, which is type-checked against the keys below.

import type { OptionFieldInfo, OptionVersionNote } from './optionSchema'

export const ROUTE_RULE_ACTION_INVENTORY = {
  route: {
    fallback_delay: { kind: 'number' },
    network_strategy: { kind: 'string' },
    outbound: { kind: 'string' },
    override_address: { kind: 'string' },
    override_port: { kind: 'number' },
    tls_fragment: { kind: 'boolean' },
    tls_fragment_fallback_delay: { kind: 'duration' },
    tls_record_fragment: { kind: 'boolean' },
    udp_connect: { kind: 'boolean' },
    udp_disable_domain_unmapping: { kind: 'boolean' },
    udp_timeout: { kind: 'duration' },
  },
  'route-options': {
    fallback_delay: { kind: 'number' },
    network_strategy: { kind: 'string' },
    override_address: { kind: 'string' },
    override_port: { kind: 'number' },
    tls_fragment: { kind: 'boolean' },
    tls_fragment_fallback_delay: { kind: 'duration' },
    tls_record_fragment: { kind: 'boolean' },
    udp_connect: { kind: 'boolean' },
    udp_disable_domain_unmapping: { kind: 'boolean' },
    udp_timeout: { kind: 'duration' },
  },
  direct: {
    bind_interface: { kind: 'string' },
    connect_timeout: { kind: 'duration' },
    domain_resolver: { kind: 'object' },
    domain_strategy: { kind: 'string', deprecated: true, since: '1.12.0', removed: '1.14.0' },
    fallback_delay: { kind: 'duration' },
    fallback_network_type: { kind: 'list', item: 'string' },
    inet4_bind_address: { kind: 'address' },
    inet6_bind_address: { kind: 'address' },
    netns: { kind: 'string' },
    network_strategy: { kind: 'string' },
    network_type: { kind: 'list', item: 'string' },
    protect_path: { kind: 'string' },
    reuse_addr: { kind: 'boolean' },
    routing_mark: { kind: 'number' },
    tcp_fast_open: { kind: 'boolean' },
    tcp_multi_path: { kind: 'boolean' },
    udp_fragment: { kind: 'boolean' },
  },
  reject: {
    method: { kind: 'string' },
    no_drop: { kind: 'boolean' },
  },
  'hijack-dns': {
  },
  sniff: {
    sniffer: { kind: 'list', item: 'string' },
    timeout: { kind: 'duration' },
  },
  resolve: {
    client_subnet: { kind: 'cidr' },
    disable_cache: { kind: 'boolean' },
    rewrite_ttl: { kind: 'number' },
    server: { kind: 'string' },
    strategy: { kind: 'string' },
  },
} as const satisfies Record<string, Record<string, OptionFieldInfo>>

/** Every RouteRuleAction type the backend registry can construct. */
export type RouteRuleActionTypeName = keyof typeof ROUTE_RULE_ACTION_INVENTORY

/**
 * The field keys valid for one RouteRuleAction type. Curation is keyed by this, so naming
 * a field sing-box does not have — or one it dropped in an upgrade — is a
 * compile error rather than an input that never binds.
 */
export type RouteRuleActionFieldKey<T extends RouteRuleActionTypeName> = Extract<
  keyof (typeof ROUTE_RULE_ACTION_INVENTORY)[T],
  string
>

export const ROUTE_RULE_ACTION_TYPE_NAMES = Object.keys(ROUTE_RULE_ACTION_INVENTORY) as RouteRuleActionTypeName[]

/**
 * Types sing-box has retired, with the versions from its own deprecation
 * table. `removed` is the one that bites: a type whose removed version is at
 * or below the INSTALLED binary is rejected, not merely discouraged.
 */
export const ROUTE_RULE_ACTION_TYPE_NOTES: Partial<Record<RouteRuleActionTypeName, OptionVersionNote>> = {
}
