package appupdate

import (
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"strconv"
	"strings"
	"time"

	"github.com/SealinGp/sing-box-easy/app/pkg/logger"
	"go.uber.org/zap"
)

// Installing our own ipk from inside the panel.
//
// The obstacle is that the panel is the thing being replaced. The package's
// prerm runs `/etc/init.d/sing-box-easy stop`, and procd does not stop a
// service by signalling one pid: it keeps every process of the instance in a
// cgroup (`/sys/fs/cgroup/services/sing-box-easy/instance1`, verified on
// iStoreOS 24.10) and can kill the whole group. An `opkg install` run as a
// child of the panel therefore dies with it, halfway through the transaction.
//
// So the install is handed to a HELPER that outlives the panel:
//
//   - it is a shell script, not this binary — the binary is what opkg replaces;
//   - it runs in its own session (Setsid), so a signal aimed at the panel's
//     process group misses it;
//   - it moves itself to the root cgroup before doing anything else, so a
//     cgroup-wide kill misses it too;
//   - it inherits none of the panel's descriptors. The panel's stdout/stderr
//     are procd pipes; a helper holding them gets SIGPIPE once procd frees the
//     dead instance.
//
// The helper also owns recovery, because once the panel is stopped nothing
// else on the router will bring it back: whatever opkg does, the script ends
// with the service enabled and running, restoring the previous binary first if
// the failed install removed it.

const (
	packageInitScript = "/etc/init.d/sing-box-easy"
	packageBinaryPath = "/usr/bin/sing-box-easy"

	// All three live in /tmp (tmpfs on OpenWrt): they must survive the panel
	// restarting, and must not wear flash or outlive a reboot.
	packageInstallScriptPath = "/tmp/sbe-package-install.sh"
	packageInstallStatePath  = "/tmp/sbe-package-install.state"
	packageInstallLogPath    = "/tmp/sbe-package-install.log"
	packageBinaryBackupPath  = "/tmp/sbe-package-install.previous"

	// packageInstallSettle is how long the helper waits before touching
	// anything, so the HTTP response that started it reaches the browser.
	packageInstallSettleSeconds = 2

	// A helper that reported "running" this long ago is not running any more.
	// A real install takes a few seconds.
	packageInstallStaleAfter = 10 * time.Minute

	// packageInstallHeadroom is the free space required beyond the size of the
	// binary being replaced.
	packageInstallHeadroom = 8 << 20

	packageInstallLogTailBytes = 4000
)

// Package install states reported to the UI.
const (
	PackageInstallRunning     = "running"
	PackageInstallSucceeded   = "succeeded"
	PackageInstallFailed      = "failed"
	PackageInstallInterrupted = "interrupted"
)

// PackageInstallResult is the outcome of the most recent panel-driven package
// install. It is read from files the helper wrote, because the process that
// started the install is by design not the one that sees it finish.
type PackageInstallResult struct {
	State       string `json:"state"`
	FromVersion string `json:"from_version"`
	ToVersion   string `json:"to_version"`
	// ExitCode is opkg's exit status; -1 while it is unknown.
	ExitCode   int    `json:"exit_code"`
	StartedAt  string `json:"started_at"`
	FinishedAt string `json:"finished_at"`
	// LogTail is the end of the helper's output: opkg's own words on a failure.
	LogTail string `json:"log_tail"`
}

// packageInstallSupported reports whether this host can run the helper.
func packageInstallSupported() bool {
	if _, err := os.Stat(packageInitScript); err != nil {
		return false
	}
	_, err := exec.LookPath("opkg")
	return err == nil
}

// shellQuote wraps a value in single quotes for /bin/sh. Every value that
// reaches the script goes through it, including the ones already constrained
// by tagPattern — the script runs as root.
func shellQuote(value string) string {
	return "'" + strings.ReplaceAll(value, "'", `'\''`) + "'"
}

// packageInstallParams is everything the helper script is generated from.
type packageInstallParams struct {
	IpkPath     string
	Downgrade   bool
	FromVersion string
	ToVersion   string
}

// buildPackageInstallScript renders the helper. Pure, so the exact script is
// testable without a router.
func buildPackageInstallScript(p packageInstallParams) string {
	flags := ""
	if p.Downgrade {
		flags = "--force-downgrade"
	}

	var b strings.Builder
	b.WriteString("#!/bin/sh\n")
	b.WriteString("# Generated by sing-box-easy: installs a prepared package while the panel is down.\n")
	fmt.Fprintf(&b, "IPK=%s\n", shellQuote(p.IpkPath))
	fmt.Fprintf(&b, "FLAGS=%s\n", shellQuote(flags))
	fmt.Fprintf(&b, "FROM=%s\n", shellQuote(p.FromVersion))
	fmt.Fprintf(&b, "TO=%s\n", shellQuote(p.ToVersion))
	fmt.Fprintf(&b, "STATE=%s\n", shellQuote(packageInstallStatePath))
	fmt.Fprintf(&b, "BIN=%s\n", shellQuote(packageBinaryPath))
	fmt.Fprintf(&b, "BACKUP=%s\n", shellQuote(packageBinaryBackupPath))
	fmt.Fprintf(&b, "INIT=%s\n", shellQuote(packageInitScript))
	fmt.Fprintf(&b, "SETTLE=%d\n", packageInstallSettleSeconds)
	b.WriteString(packageInstallScriptBody)
	return b.String()
}

// packageInstallScriptBody is the fixed part of the helper. POSIX sh only:
// it runs under BusyBox ash.
const packageInstallScriptBody = `
# Leave procd's service cgroup FIRST. Stopping the panel can kill every process
# in that group, and this script must outlive the panel.
if [ -w /sys/fs/cgroup/cgroup.procs ]; then
	echo $$ > /sys/fs/cgroup/cgroup.procs 2>/dev/null
fi

STARTED=$(date +%s)

# write_state <state> <exit_code> <finished_at> — atomic, so a reader never
# sees half a file.
write_state() {
	{
		echo "state=$1"
		echo "exit_code=$2"
		echo "from=$FROM"
		echo "to=$TO"
		echo "started_at=$STARTED"
		echo "finished_at=$3"
	} > "$STATE.tmp" && mv "$STATE.tmp" "$STATE"
}

panel_pid() {
	set -- $(pidof sing-box-easy)
	echo "$1"
}

write_state running "" ""

# Let the HTTP response that started this reach the browser.
sleep "$SETTLE"

old_pid=$(panel_pid)
cp -p "$BIN" "$BACKUP" 2>/dev/null

echo "== $(date) opkg install $FLAGS $IPK"
# FLAGS is deliberately unquoted: it is empty or one flag.
opkg install $FLAGS "$IPK"
code=$?
echo "== opkg exited with $code"

if [ "$code" -ne 0 ] && [ ! -x "$BIN" ] && [ -f "$BACKUP" ]; then
	echo "== the install removed the binary; restoring the previous one"
	cp -p "$BACKUP" "$BIN"
fi

# Whatever happened above, the panel must end up enabled and running: prerm
# disables as well as stops, and nothing else on the router brings it back.
"$INIT" enable
sleep 1
new_pid=$(panel_pid)
if [ -z "$new_pid" ]; then
	echo "== the panel is not running; starting it"
	"$INIT" start
elif [ "$code" -eq 0 ] && [ "$new_pid" = "$old_pid" ]; then
	# The package was replaced under a process that never stopped: it is still
	# the old binary in memory.
	echo "== the panel was not restarted by the install; restarting it"
	"$INIT" restart
fi

if [ "$code" -eq 0 ]; then
	write_state succeeded "$code" "$(date +%s)"
	rm -f "$IPK"
else
	write_state failed "$code" "$(date +%s)"
fi
rm -f "$BACKUP"
echo "== done"
`

// parsePackageInstallState turns the helper's state file into a result.
// Returns nil when the file holds no usable state.
func parsePackageInstallState(data []byte, logTail string, now time.Time) *PackageInstallResult {
	fields := map[string]string{}
	for _, line := range strings.Split(string(data), "\n") {
		key, value, found := strings.Cut(strings.TrimSpace(line), "=")
		if found {
			fields[key] = value
		}
	}

	state := fields["state"]
	switch state {
	case PackageInstallRunning, PackageInstallSucceeded, PackageInstallFailed:
	default:
		return nil
	}

	result := &PackageInstallResult{
		State:       state,
		FromVersion: fields["from"],
		ToVersion:   fields["to"],
		ExitCode:    -1,
		LogTail:     logTail,
	}
	if code, err := strconv.Atoi(fields["exit_code"]); err == nil {
		result.ExitCode = code
	}

	started, startedOK := parseUnixSeconds(fields["started_at"])
	if startedOK {
		result.StartedAt = started.UTC().Format(time.RFC3339)
	}
	if finished, ok := parseUnixSeconds(fields["finished_at"]); ok {
		result.FinishedAt = finished.UTC().Format(time.RFC3339)
	}

	// "running" with no finish long after it began means the helper died (a
	// reboot does not count: /tmp is gone with it). Reporting it as running
	// forever would lock the UI on a spinner.
	if state == PackageInstallRunning && (!startedOK || now.Sub(started) > packageInstallStaleAfter) {
		result.State = PackageInstallInterrupted
	}
	return result
}

func parseUnixSeconds(value string) (time.Time, bool) {
	seconds, err := strconv.ParseInt(strings.TrimSpace(value), 10, 64)
	if err != nil || seconds <= 0 {
		return time.Time{}, false
	}
	return time.Unix(seconds, 0), true
}

// ReadPackageInstallResult reports the most recent panel-driven package
// install, or nil when there has been none since boot.
func ReadPackageInstallResult() *PackageInstallResult {
	data, err := os.ReadFile(packageInstallStatePath)
	if err != nil {
		return nil
	}
	return parsePackageInstallState(data, readTail(packageInstallLogPath, packageInstallLogTailBytes), time.Now())
}

// readTail returns up to limit bytes from the end of a file, or "".
func readTail(path string, limit int) string {
	data, err := os.ReadFile(path)
	if err != nil {
		return ""
	}
	if len(data) > limit {
		data = data[len(data)-limit:]
	}
	return strings.TrimSpace(string(data))
}

// fileSHA256 hashes a file on disk.
func fileSHA256(path string) (string, error) {
	file, err := os.Open(path)
	if err != nil {
		return "", err
	}
	defer file.Close()

	hash := sha256.New()
	if _, err := io.Copy(hash, file); err != nil {
		return "", err
	}
	return hex.EncodeToString(hash.Sum(nil)), nil
}

// checkInstallablePlan decides whether a prepared package may be installed
// without an operator looking at it. Stricter than what the manual path
// tolerates: there, a person reads "not verified" and chooses.
func checkInstallablePlan(plan *IpkPlan) error {
	if plan == nil {
		return fmt.Errorf("the package has not been prepared yet")
	}
	if !plan.Verified {
		return fmt.Errorf("this release publishes no checksum, so the package cannot be verified; " +
			"install it manually with the command shown")
	}

	sum, err := fileSHA256(plan.Path)
	if err != nil {
		return fmt.Errorf("the prepared package is no longer on the router (%v); prepare it again", err)
	}
	// The file sat in /tmp between prepare and install. It is installed as
	// root, so it is re-read rather than trusted to be what was verified.
	if sum != plan.SHA256 {
		return fmt.Errorf("the prepared package changed on disk since it was verified; prepare it again")
	}
	return nil
}

// checkInstallSpace refuses an install the filesystem cannot hold. Running out
// of space mid-install is the failure that leaves no binary behind.
func checkInstallSpace() error {
	stat, err := os.Stat(packageBinaryPath)
	if err != nil {
		return fmt.Errorf("cannot inspect the installed binary: %w", err)
	}
	free, err := freeBytes(filepath.Dir(packageBinaryPath))
	if err != nil {
		return fmt.Errorf("cannot determine free space: %w", err)
	}
	need := uint64(stat.Size()) + packageInstallHeadroom
	if free < need {
		return fmt.Errorf("not enough free space to install safely: %d MB free, %d MB needed",
			free>>20, need>>20)
	}
	return nil
}

// StartIpkInstall installs a package that a prepare task already downloaded
// and verified, then lets the panel be restarted by it.
//
// It takes the ID of that task rather than a path or a version: the file to
// install as root is then one this process fetched and checked, never a value
// from the request.
//
// The returned task is already `restarting` — from here the outcome is
// reported by ReadPackageInstallResult, since this process will not be the one
// to see the install finish.
func (u *Updater) StartIpkInstall(prepareTaskID string) (*Task, error) {
	info := DetectSelfUpdate()
	if info.Method != SelfUpdateOpkg {
		return nil, fmt.Errorf("this instance was not installed via opkg; use the standard update instead")
	}
	if !info.InstallSupported {
		return nil, fmt.Errorf("this host cannot install the package automatically; " +
			"run the command shown instead")
	}

	prepared, err := u.GetTask(strings.TrimSpace(prepareTaskID))
	if err != nil {
		return nil, fmt.Errorf("the prepared package was not found; prepare it again")
	}
	snapshot := prepared.Snapshot()
	if snapshot.Status != StatusCompleted {
		return nil, fmt.Errorf("the package is not ready yet (task is %s)", snapshot.Status)
	}
	plan := snapshot.Plan
	if err := checkInstallablePlan(plan); err != nil {
		return nil, err
	}
	if err := checkInstallSpace(); err != nil {
		return nil, err
	}
	if last := ReadPackageInstallResult(); last != nil && last.State == PackageInstallRunning {
		return nil, fmt.Errorf("a package install is already in progress")
	}

	script := buildPackageInstallScript(packageInstallParams{
		IpkPath:     plan.Path,
		Downgrade:   CompareVersions(plan.Version, Current()) < 0,
		FromVersion: Current(),
		ToVersion:   plan.Version,
	})

	u.mu.Lock()
	if u.running != nil && !u.running.isTerminal() {
		id := u.running.id
		u.mu.Unlock()
		return nil, fmt.Errorf("an update is already in progress (task %s)", id)
	}
	task := &Task{
		id:          fmt.Sprintf("pkg_%d", time.Now().UnixNano()),
		status:      StatusRestarting,
		message:     "Installing the package; the panel will restart",
		progress:    100,
		fromVersion: Current(),
		toVersion:   plan.Version,
	}
	u.tasks[task.id] = task
	u.running = task
	u.mu.Unlock()

	// A stale state file would be read back as this run's result.
	_ = os.Remove(packageInstallStatePath)

	if err := os.WriteFile(packageInstallScriptPath, []byte(script), 0o700); err != nil {
		task.fail(err)
		return nil, fmt.Errorf("failed to write the install helper: %w", err)
	}
	if err := launchDetached(packageInstallScriptPath, packageInstallLogPath); err != nil {
		task.fail(err)
		return nil, fmt.Errorf("failed to start the install helper: %w", err)
	}

	logger.Info("Package install handed to the detached helper",
		zap.String("task_id", task.id),
		zap.String("package", plan.Path),
		zap.String("from", task.fromVersion),
		zap.String("to", task.toVersion),
	)
	return task, nil
}
